### ISSUE TITLE
Morning code review

### ISSUE THREAD

**Issue by dili021** [dili021/HTML-forms#2]

**Comment by Kyle-Law** [comment]
Few recommendations to make your CSS codes tidier. Codes between /* */ are commented out.
1) .logos {
	    **display: flex;**
	    **justify-content: center;**
	    /* position: relative; */
	    /* left: 40%; */
	    /* top: 160px; */
	    /* margin-bottom: 180px; */
	    /* justify-content: space-between; */
	    /* width: 150px; */
	}
2) .header {
    **display: flex;**
    **justify-content: flex-end;**
    /* position: absolute; */
    /* right: 0; */
    /* justify-content: end; */
	}

3).main-logo {
    **display: flex;**
    **justify-content: center;**
    /* position: relative; */
    /* top: 150px; */
    /* width: auto;*/
	}
